name: ML Model CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code + DVC
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install scikit-learn==1.0.2
          pip install pytest==7.1.2
          pip install joblib==1.1.0
          pip install dvc==2.10.2


      # - name: Run Model Tests
      #   run: pytest tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code + DVC
        uses: actions/checkout@v2

      - name: Set Up DVC
        run: pip install dvc

      - name: Configure DVC Remote
        run: |
          dvc init -f
          dvc remote add origin https://dagshub.com/${{ secrets.DAGSHUB_USER }}/${{ secrets.REPO_NAME }}.dvc
          dvc remote default origin
# dvc remote add origin https://dagshub.com/k.sithvothy12/github-action-demo.dvc

      - name: Authenticate with DAGsHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://${{ secrets.DAGSHUB_USER }}:${{ secrets.DAGSHUB_TOKEN }}@dagshub.com/${{ secrets.DAGSHUB_USER }}/${{ secrets.REPO_NAME }}.git

      - name: Push Model to DAGsHub
        run: |
          dvc add IRIS-model.pkl
          git add IRIS-model.pkl.dvc
          git commit -m "Update model via CI/CD"
          git push origin main
          dvc push